### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by logancyang** [Make-md/makemd#376]
Just installed the plugin on Obsidian v1.7.4. 

I see this error in my dev console repeating forever

```
Uncaught RangeError: Maximum call stack size exceeded
    at t.get (app.js:1:2343815)
    at t.eval (plugin:make-md:921:20557)
    at t.o [as getActiveViewOfType] (plugin:make-md:921:19114)
    at t.get (app.js:1:2343849)
    at t.eval (plugin:make-md:921:20557)
    at t.o [as getActiveViewOfType] (plugin:make-md:921:19114)
    at t.get (app.js:1:2343849)
    at t.eval (plugin:make-md:921:20557)
    at t.o [as getActiveViewOfType] (plugin:make-md:921:19114)
    at t.get (app.js:1:2343849)
```

**Comment by Adamkadaban** [comment]
I've been getting this error as well. With no copilot installed

**Comment by jp-cen** [comment]
This issue originated from some changes in Obsidian’s latest version and has been patched
________________________________
De : Adam Hassan ***@***.***>
Envoyé : Friday, October 18, 2024 11:57:43 AM
À : Make-md/makemd ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [Make-md/makemd] Uncaught RangeError: Maximum call stack size exceeded (Issue #376)


I've been getting this error as well. With no copilot installed
